name: Installing dependencies
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
      - develop
    tags:
      - v*
jobs:
  nodejs:
    name: Tests of releases NodeJS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
          - 15.x
    steps:
      - uses: actions/checkout@v2
      - name: 'Install nodejs dependencies ${{ matrix.node-version }}'''
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
      - run: |
          npm install -D
          npm install
  build_app:
    name: Build App (desktop)
    needs:
      - nodejs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run make
      - name: Upload App Compiled (.deb)
        uses: actions/upload-artifact@v2.1.4
        with:
          name: MiniVideo(webcam).deb
          path: out/make/deb/x64/*.deb
      - name: Upload App Compiled (.rpm)
        uses: actions/upload-artifact@v2.1.4
        with:
          name: MiniVideo(webcam).rpm
          path: out/make/rpm/x64/*.rpm

